# Generated by Django 4.2.25 on 2025-10-20 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_consultations', models.PositiveIntegerField(default=0, help_text='Total number of consultations')),
                ('medical_consultations', models.PositiveIntegerField(default=0, help_text='Number of medical consultations')),
                ('dental_consultations', models.PositiveIntegerField(default=0, help_text='Number of dental consultations')),
                ('total_appointments', models.PositiveIntegerField(default=0, help_text='Total appointments scheduled')),
                ('completed_appointments', models.PositiveIntegerField(default=0, help_text='Completed appointments')),
                ('cancelled_appointments', models.PositiveIntegerField(default=0, help_text='Cancelled appointments')),
                ('no_show_appointments', models.PositiveIntegerField(default=0, help_text='No-show appointments')),
                ('certificates_issued', models.PositiveIntegerField(default=0, help_text='Number of certificates issued')),
                ('prescriptions_issued', models.PositiveIntegerField(default=0, help_text='Number of prescriptions issued')),
                ('new_students_registered', models.PositiveIntegerField(default=0, help_text='New student registrations')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consultation statistic',
                'verbose_name_plural': 'consultation statistics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_c_period__c86dcc_idx')],
                'unique_together': {('period_type', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='MorbidityStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Type of time period', max_length=10)),
                ('period_start', models.DateField(help_text='Start date of the period')),
                ('period_end', models.DateField(help_text='End date of the period')),
                ('diagnosis', models.CharField(help_text='Diagnosis or condition name', max_length=500)),
                ('record_type', models.CharField(choices=[('medical', 'Medical'), ('dental', 'Dental')], default='medical', max_length=10)),
                ('case_count', models.PositiveIntegerField(default=0, help_text='Number of cases for this diagnosis')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total cases', max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'morbidity statistic',
                'verbose_name_plural': 'morbidity statistics',
                'ordering': ['-period_start', '-case_count'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='analytics_m_period__a5d9c6_idx'), models.Index(fields=['diagnosis'], name='analytics_m_diagnos_8ed261_idx'), models.Index(fields=['record_type'], name='analytics_m_record__94df65_idx')],
                'unique_together': {('period_type', 'period_start', 'diagnosis', 'record_type')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('morbidity', 'Morbidity Report'), ('consultation', 'Consultation Report'), ('appointments', 'Appointments Report'), ('students', 'Student Registry Report'), ('certificates', 'Certificates Report'), ('custom', 'Custom Report')], max_length=20)),
                ('report_name', models.CharField(help_text='Report title/name', max_length=200)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('report_file', models.FileField(help_text='Generated report file', upload_to='reports/%Y/%m/')),
                ('filters_applied', models.TextField(blank=True, help_text='JSON string of filters used', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('generated_by', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated report',
                'verbose_name_plural': 'generated reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='analytics_g_report__199bb5_idx'), models.Index(fields=['generated_by'], name='analytics_g_generat_088d39_idx')],
            },
        ),
    ]
