# Generated by Django 4.2.25 on 2025-10-20 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(editable=False, help_text='Unique ticket number for appointment', max_length=20, unique=True)),
                ('service_type', models.CharField(choices=[('medical_consultation', 'Medical Consultation'), ('dental_cleaning', 'Dental Cleaning'), ('dental_filling', 'Dental Filling'), ('dental_extraction', 'Dental Extraction'), ('medical_clearance', 'Medical Clearance'), ('health_certificate', 'Health Certificate'), ('vaccination', 'Vaccination'), ('physical_exam', 'Physical Examination'), ('follow_up', 'Follow-up Consultation'), ('emergency', 'Emergency'), ('other', 'Other')], help_text='Type of service requested', max_length=30)),
                ('preferred_date', models.DateField(help_text='Preferred appointment date')),
                ('preferred_time_slot', models.CharField(choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (1:00 PM - 5:00 PM)')], default='morning', help_text='Preferred time slot', max_length=10)),
                ('actual_datetime', models.DateTimeField(blank=True, help_text='Actual scheduled date and time (set by doctor)', null=True)),
                ('reason', models.TextField(help_text='Reason for appointment / Chief complaint')),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes from doctor', null=True)),
                ('emergency_contact_name', models.CharField(help_text='Emergency contact name', max_length=200)),
                ('emergency_contact_number', models.CharField(help_text='Emergency contact number', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved/Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', help_text='Appointment status', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether reminder notification was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, help_text='Assigned doctor (set upon approval)', limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-preferred_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note or comment')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note (not visible to student)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='appointments.appointment')),
                ('author', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'appointment note',
                'verbose_name_plural': 'appointment notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['student', 'status'], name='appointment_student_632237_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status'], name='appointment_doctor__0653d1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['preferred_date', 'status'], name='appointment_preferr_ca1825_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['ticket_number'], name='appointment_ticket__8dc0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appointment_created_5f1d98_idx'),
        ),
    ]
