# Generated by Django 4.2.25 on 2025-11-05 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
