#!/usr/bin/env python
"""
Database ERD Generator for TIP MDS EMR
Converts database schema to Mermaid ERD format
"""

def generate_erd():
    """Generate Mermaid ERD diagram"""
    
    erd = []
    erd.append('erDiagram')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% ACCOUNTS APP - User Management')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    users {')
    erd.append('        integer id PK')
    erd.append('        varchar email UK "unique, not null"')
    erd.append('        varchar password "not null"')
    erd.append('        varchar role "student, doctor, admin"')
    erd.append('        varchar first_name')
    erd.append('        varchar last_name')
    erd.append('        varchar phone_number')
    erd.append('        boolean is_active')
    erd.append('        boolean is_staff')
    erd.append('        boolean is_superuser')
    erd.append('        timestamp date_joined')
    erd.append('        timestamp last_login')
    erd.append('    }')
    erd.append('')
    erd.append('    user_profiles {')
    erd.append('        integer user_id PK,FK')
    erd.append('        varchar avatar')
    erd.append('        text address')
    erd.append('        date date_of_birth')
    erd.append('        varchar emergency_contact_name')
    erd.append('        varchar emergency_contact_number')
    erd.append('        varchar emergency_contact_relationship')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    doctor_profiles {')
    erd.append('        integer user_id PK,FK')
    erd.append('        varchar license_number UK "unique, not null"')
    erd.append('        varchar specialization')
    erd.append('        varchar department')
    erd.append('        integer years_of_experience')
    erd.append('        text qualifications')
    erd.append('        varchar office_location')
    erd.append('        text consultation_hours')
    erd.append('        varchar signature_image')
    erd.append('        boolean is_active')
    erd.append('        boolean is_available_for_appointments')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% STUDENTS APP - Student Profiles & Records')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    student_profiles {')
    erd.append('        integer user_id PK,FK')
    erd.append('        varchar student_id UK "unique, not null"')
    erd.append('        varchar program "CS, IT, CE, EE"')
    erd.append('        varchar year_level "1-5"')
    erd.append('        varchar sex "M, F"')
    erd.append('        date date_of_birth')
    erd.append('        varchar contact_number')
    erd.append('        text address')
    erd.append('        varchar emergency_contact_name')
    erd.append('        varchar emergency_contact_relationship')
    erd.append('        varchar emergency_contact_number')
    erd.append('        text emergency_contact_address')
    erd.append('        decimal height_cm')
    erd.append('        decimal weight_kg')
    erd.append('        varchar blood_type')
    erd.append('        text allergies')
    erd.append('        text current_medications')
    erd.append('        text immunization_history')
    erd.append('        text medical_history')
    erd.append('        date last_dental_visit')
    erd.append('        text oral_habits')
    erd.append('        text dental_history')
    erd.append('        boolean is_complete')
    erd.append('        boolean is_verified')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    medical_records {')
    erd.append('        uuid id PK')
    erd.append('        integer student_id FK')
    erd.append('        integer doctor_id FK')
    erd.append('        integer approved_by_id FK')
    erd.append('        varchar record_type "medical, dental"')
    erd.append('        date visit_date')
    erd.append('        text chief_complaint')
    erd.append('        text diagnosis')
    erd.append('        text procedure')
    erd.append('        text prescription')
    erd.append('        text remarks')
    erd.append('        varchar blood_pressure')
    erd.append('        decimal temperature')
    erd.append('        integer pulse_rate')
    erd.append('        integer respiratory_rate')
    erd.append('        varchar lab_results')
    erd.append('        varchar xray_image')
    erd.append('        varchar attachments')
    erd.append('        varchar status "pending, approved, declined"')
    erd.append('        timestamp approved_at')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    record_update_requests {')
    erd.append('        uuid id PK')
    erd.append('        integer student_id FK')
    erd.append('        integer reviewed_by_id FK')
    erd.append('        varchar field_name')
    erd.append('        text old_value')
    erd.append('        text new_value')
    erd.append('        text reason')
    erd.append('        varchar supporting_document')
    erd.append('        varchar status "pending, approved, declined"')
    erd.append('        text review_notes')
    erd.append('        timestamp reviewed_at')
    erd.append('        timestamp created_at')
    erd.append('        timestamp expiry_date')
    erd.append('    }')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% APPOINTMENTS APP - Scheduling')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    appointments {')
    erd.append('        uuid id PK')
    erd.append('        varchar ticket_number UK')
    erd.append('        integer student_id FK')
    erd.append('        integer doctor_id FK')
    erd.append('        integer approved_by_id FK')
    erd.append('        varchar service_type')
    erd.append('        date preferred_date')
    erd.append('        varchar preferred_time_slot')
    erd.append('        timestamp actual_datetime')
    erd.append('        text reason')
    erd.append('        text doctor_notes')
    erd.append('        varchar emergency_contact_name')
    erd.append('        varchar emergency_contact_number')
    erd.append('        varchar status "pending, approved, completed"')
    erd.append('        timestamp approved_at')
    erd.append('        timestamp completed_at')
    erd.append('        timestamp cancelled_at')
    erd.append('        text cancellation_reason')
    erd.append('        boolean reminder_sent')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    appointment_notes {')
    erd.append('        integer id PK')
    erd.append('        uuid appointment_id FK')
    erd.append('        integer author_id FK')
    erd.append('        text note')
    erd.append('        boolean is_internal')
    erd.append('        timestamp created_at')
    erd.append('    }')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% TEMPLATES_DOCS APP - Certificates & Prescriptions')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    templates {')
    erd.append('        uuid id PK')
    erd.append('        integer created_by_id FK')
    erd.append('        varchar name')
    erd.append('        varchar template_type')
    erd.append('        text description')
    erd.append('        text template_html')
    erd.append('        text template_css')
    erd.append('        varchar header_image')
    erd.append('        text footer_text')
    erd.append('        boolean is_active')
    erd.append('        boolean is_default')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    issued_certificates {')
    erd.append('        uuid id PK')
    erd.append('        varchar certificate_number UK')
    erd.append('        integer student_id FK')
    erd.append('        integer doctor_id FK')
    erd.append('        uuid template_id FK')
    erd.append('        varchar title')
    erd.append('        text purpose')
    erd.append('        text diagnosis')
    erd.append('        text prescription')
    erd.append('        text remarks')
    erd.append('        date date_issued')
    erd.append('        date valid_until')
    erd.append('        varchar pdf_file')
    erd.append('        varchar status "active, expired, revoked"')
    erd.append('        timestamp revoked_at')
    erd.append('        text revocation_reason')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    prescriptions {')
    erd.append('        uuid id PK')
    erd.append('        varchar prescription_number UK')
    erd.append('        integer student_id FK')
    erd.append('        integer doctor_id FK')
    erd.append('        text diagnosis')
    erd.append('        text medications')
    erd.append('        text instructions')
    erd.append('        date date_issued')
    erd.append('        date valid_until')
    erd.append('        varchar pdf_file')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% ANALYTICS APP - Statistics & Reports')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    morbidity_statistics {')
    erd.append('        uuid id PK')
    erd.append('        integer generated_by_id FK')
    erd.append('        varchar period_type "daily, weekly, monthly"')
    erd.append('        date period_start')
    erd.append('        date period_end')
    erd.append('        varchar diagnosis')
    erd.append('        varchar record_type')
    erd.append('        integer case_count')
    erd.append('        decimal percentage')
    erd.append('        timestamp generated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    consultation_statistics {')
    erd.append('        uuid id PK')
    erd.append('        varchar period_type')
    erd.append('        date period_start')
    erd.append('        date period_end')
    erd.append('        integer total_consultations')
    erd.append('        integer medical_consultations')
    erd.append('        integer dental_consultations')
    erd.append('        integer total_appointments')
    erd.append('        integer completed_appointments')
    erd.append('        integer cancelled_appointments')
    erd.append('        integer no_show_appointments')
    erd.append('        integer certificates_issued')
    erd.append('        integer prescriptions_issued')
    erd.append('        integer new_students_registered')
    erd.append('        timestamp generated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    generated_reports {')
    erd.append('        uuid id PK')
    erd.append('        integer generated_by_id FK')
    erd.append('        varchar report_type')
    erd.append('        varchar report_name')
    erd.append('        varchar format "pdf, csv, excel"')
    erd.append('        date date_from')
    erd.append('        date date_to')
    erd.append('        varchar report_file')
    erd.append('        text filters_applied')
    erd.append('        integer download_count')
    erd.append('        timestamp generated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% NOTIFICATIONS APP - User Notifications')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    notifications {')
    erd.append('        uuid id PK')
    erd.append('        integer recipient_id FK')
    erd.append('        varchar notification_type')
    erd.append('        varchar title')
    erd.append('        text message')
    erd.append('        varchar priority "low, normal, high"')
    erd.append('        varchar action_url')
    erd.append('        varchar action_label')
    erd.append('        varchar related_object_type')
    erd.append('        varchar related_object_id')
    erd.append('        boolean is_read')
    erd.append('        timestamp read_at')
    erd.append('        boolean send_email')
    erd.append('        boolean email_sent')
    erd.append('        timestamp email_sent_at')
    erd.append('        timestamp created_at')
    erd.append('        timestamp expires_at')
    erd.append('    }')
    erd.append('')
    erd.append('    email_logs {')
    erd.append('        uuid id PK')
    erd.append('        uuid notification_id FK')
    erd.append('        varchar recipient_email')
    erd.append('        varchar recipient_name')
    erd.append('        varchar subject')
    erd.append('        text body')
    erd.append('        varchar status "pending, sent, failed"')
    erd.append('        text error_message')
    erd.append('        integer retry_count')
    erd.append('        integer max_retries')
    erd.append('        timestamp created_at')
    erd.append('        timestamp sent_at')
    erd.append('    }')
    erd.append('')
    erd.append('    notification_preferences {')
    erd.append('        integer user_id PK,FK')
    erd.append('        boolean email_appointment_approved')
    erd.append('        boolean email_appointment_reminder')
    erd.append('        boolean email_request_status')
    erd.append('        boolean email_certificate_issued')
    erd.append('        boolean email_system_notifications')
    erd.append('        boolean inapp_appointment_updates')
    erd.append('        boolean inapp_request_updates')
    erd.append('        boolean inapp_system_notifications')
    erd.append('        integer appointment_reminder_hours')
    erd.append('        timestamp created_at')
    erd.append('        timestamp updated_at')
    erd.append('    }')
    erd.append('')
    erd.append('    %% ========================================')
    erd.append('    %% RELATIONSHIPS')
    erd.append('    %% ========================================')
    erd.append('')
    erd.append('    %% User Relationships')
    erd.append('    users ||--o| user_profiles : has')
    erd.append('    users ||--o| doctor_profiles : has')
    erd.append('    users ||--o| student_profiles : has')
    erd.append('    users ||--o| notification_preferences : has')
    erd.append('')
    erd.append('    %% Student Relationships')
    erd.append('    student_profiles ||--o{ medical_records : has')
    erd.append('    student_profiles ||--o{ record_update_requests : submits')
    erd.append('    student_profiles ||--o{ appointments : books')
    erd.append('    student_profiles ||--o{ issued_certificates : receives')
    erd.append('    student_profiles ||--o{ prescriptions : receives')
    erd.append('')
    erd.append('    %% Doctor Relationships')
    erd.append('    users ||--o{ medical_records : creates')
    erd.append('    users ||--o{ appointments : handles')
    erd.append('    users ||--o{ issued_certificates : issues')
    erd.append('    users ||--o{ prescriptions : issues')
    erd.append('    users ||--o{ templates : creates')
    erd.append('')
    erd.append('    %% Approval Relationships')
    erd.append('    users ||--o{ medical_records : approves')
    erd.append('    users ||--o{ appointments : approves')
    erd.append('    users ||--o{ record_update_requests : reviews')
    erd.append('')
    erd.append('    %% Document Relationships')
    erd.append('    templates ||--o{ issued_certificates : uses')
    erd.append('    appointments ||--o{ appointment_notes : has')
    erd.append('')
    erd.append('    %% Analytics Relationships')
    erd.append('    users ||--o{ morbidity_statistics : generates')
    erd.append('    users ||--o{ generated_reports : generates')
    erd.append('')
    erd.append('    %% Notification Relationships')
    erd.append('    users ||--o{ notifications : receives')
    erd.append('    notifications ||--o| email_logs : triggers')
    erd.append('    users ||--o{ appointment_notes : writes')
    
    return '\n'.join(erd)

def generate_compact_erd():
    """Generate a more compact, high-level ERD"""
    
    erd = []
    erd.append('erDiagram')
    erd.append('')
    erd.append('    %% Simplified ERD - Main Entities Only')
    erd.append('')
    erd.append('    USERS {')
    erd.append('        int id PK')
    erd.append('        string email UK')
    erd.append('        string role "student|doctor|admin"')
    erd.append('        string name')
    erd.append('        boolean is_active')
    erd.append('    }')
    erd.append('')
    erd.append('    STUDENT_PROFILES {')
    erd.append('        int user_id PK,FK')
    erd.append('        string student_id UK')
    erd.append('        string program')
    erd.append('        string year_level')
    erd.append('        text medical_info')
    erd.append('        boolean is_verified')
    erd.append('    }')
    erd.append('')
    erd.append('    DOCTOR_PROFILES {')
    erd.append('        int user_id PK,FK')
    erd.append('        string license_number UK')
    erd.append('        string specialization')
    erd.append('        string department')
    erd.append('        boolean is_available')
    erd.append('    }')
    erd.append('')
    erd.append('    MEDICAL_RECORDS {')
    erd.append('        uuid id PK')
    erd.append('        int student_id FK')
    erd.append('        int doctor_id FK')
    erd.append('        string record_type')
    erd.append('        text diagnosis')
    erd.append('        text prescription')
    erd.append('        string status')
    erd.append('    }')
    erd.append('')
    erd.append('    APPOINTMENTS {')
    erd.append('        uuid id PK')
    erd.append('        string ticket_number UK')
    erd.append('        int student_id FK')
    erd.append('        int doctor_id FK')
    erd.append('        date preferred_date')
    erd.append('        string status')
    erd.append('    }')
    erd.append('')
    erd.append('    CERTIFICATES {')
    erd.append('        uuid id PK')
    erd.append('        string certificate_number UK')
    erd.append('        int student_id FK')
    erd.append('        int doctor_id FK')
    erd.append('        string title')
    erd.append('        date date_issued')
    erd.append('    }')
    erd.append('')
    erd.append('    NOTIFICATIONS {')
    erd.append('        uuid id PK')
    erd.append('        int recipient_id FK')
    erd.append('        string type')
    erd.append('        text message')
    erd.append('        boolean is_read')
    erd.append('    }')
    erd.append('')
    erd.append('    %% Relationships')
    erd.append('    USERS ||--o| STUDENT_PROFILES : "is"')
    erd.append('    USERS ||--o| DOCTOR_PROFILES : "is"')
    erd.append('    STUDENT_PROFILES ||--o{ MEDICAL_RECORDS : "has"')
    erd.append('    DOCTOR_PROFILES ||--o{ MEDICAL_RECORDS : "creates"')
    erd.append('    STUDENT_PROFILES ||--o{ APPOINTMENTS : "books"')
    erd.append('    DOCTOR_PROFILES ||--o{ APPOINTMENTS : "handles"')
    erd.append('    DOCTOR_PROFILES ||--o{ CERTIFICATES : "issues"')
    erd.append('    STUDENT_PROFILES ||--o{ CERTIFICATES : "receives"')
    erd.append('    USERS ||--o{ NOTIFICATIONS : "receives"')
    
    return '\n'.join(erd)

def main():
    print("Generating Database ERD Diagrams...\n")
    
    # Generate detailed ERD
    print("Creating detailed ERD (all 18 tables)...")
    detailed = generate_erd()
    with open('database_erd_detailed.mmd', 'w', encoding='utf-8') as f:
        f.write(detailed)
    print("Saved: database_erd_detailed.mmd")
    
    # Generate compact ERD
    print("Creating compact ERD (main entities only)...")
    compact = generate_compact_erd()
    with open('database_erd_compact.mmd', 'w', encoding='utf-8') as f:
        f.write(compact)
    print("Saved: database_erd_compact.mmd")
    
    print("\nDatabase ERD Diagrams Generated!")
    print("\nFiles created:")
    print("  1. database_erd_detailed.mmd  -> Complete schema (18 tables)")
    print("  2. database_erd_compact.mmd   -> Simplified view (7 main entities)")
    
    print("\nDiagram Statistics:")
    print("  - Total Tables: 18")
    print("  - Accounts App: 3 tables")
    print("  - Students App: 3 tables")
    print("  - Appointments App: 2 tables")
    print("  - Templates/Docs App: 3 tables")
    print("  - Analytics App: 3 tables")
    print("  - Notifications App: 3 tables")
    print("  - Django Admin: 1 table")
    
    print("\nView your ERD:")
    print("  - Open: https://mermaid.live/")
    print("  - Copy content from .mmd files")
    print("  - Paste into editor")
    print("\nTip: Use detailed ERD for documentation")
    print("     Use compact ERD for presentations")

if __name__ == '__main__':
    main()