# Generated by Django 4.2.25 on 2025-10-20 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name for identification', max_length=200)),
                ('template_type', models.CharField(choices=[('medical_certificate', 'Medical Certificate'), ('dental_certificate', 'Dental Certificate'), ('medical_clearance', 'Medical Clearance'), ('health_certificate', 'Health Certificate'), ('prescription', 'E-Prescription'), ('lab_request', 'Laboratory Request'), ('referral', 'Referral Letter'), ('excuse_letter', 'Excuse Letter'), ('other', 'Other')], help_text='Type of document template', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of template usage', null=True)),
                ('template_html', models.TextField(help_text='HTML template with placeholders. Use {{variable_name}} for dynamic content. Available variables: student_name, student_id, date, diagnosis, etc.')),
                ('template_css', models.TextField(blank=True, help_text='CSS styles for PDF generation', null=True)),
                ('header_image', models.ImageField(blank=True, help_text='Header image/logo for template', null=True, upload_to='templates/headers/')),
                ('footer_text', models.TextField(blank=True, help_text='Footer text for template', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is currently in use')),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('diagnosis', models.TextField(help_text='Diagnosis or condition')),
                ('medications', models.TextField(help_text='List of medications with dosage and frequency. Format: Drug name - Dosage - Frequency - Duration')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for patient', null=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, help_text='Prescription validity period', null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_issued', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'ordering': ['-date_issued', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(editable=False, help_text='Unique certificate number', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Certificate title/subject', max_length=200)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of certificate', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnosis or medical condition', null=True)),
                ('prescription', models.TextField(blank=True, help_text='Prescribed medications', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or instructions', null=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now, help_text='Date certificate was issued')),
                ('valid_until', models.DateField(blank=True, help_text='Expiration date of certificate', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF file', null=True, upload_to='certificates/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', help_text='Certificate status', max_length=10)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason for revocation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='students.studentprofile')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='templates_docs.template')),
            ],
            options={
                'verbose_name': 'issued certificate',
                'verbose_name_plural': 'issued certificates',
                'ordering': ['-date_issued', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['template_type', 'is_active'], name='templates_d_templat_e5a9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_default'], name='templates_d_is_defa_36fdc2_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='templates_d_prescri_762008_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['student', 'date_issued'], name='templates_d_student_07ec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['certificate_number'], name='templates_d_certifi_b855cc_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['student', 'status'], name='templates_d_student_77875f_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['date_issued', 'status'], name='templates_d_date_is_60099b_idx'),
        ),
        migrations.AddIndex(
            model_name='issuedcertificate',
            index=models.Index(fields=['valid_until'], name='templates_d_valid_u_aa97dd_idx'),
        ),
    ]
