# Generated by Django 4.2.25 on 2025-11-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctors_doc_license_49ebb1_idx',
            old_name='doctors_doc_license_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctors_doc_special_a5690e_idx',
            old_name='doctors_doc_special_idx',
        ),
        migrations.RenameIndex(
            model_name='doctorprofile',
            new_name='doctors_doc_is_acti_205e6f_idx',
            old_name='doctors_doc_is_acti_idx',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='Whether doctor has completed their profile setup'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary password for first login (plain text for display only)', max_length=255, null=True),
        ),
    ]
