# Generated by Django 4.2.25 on 2025-10-20 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_appointment_approved', models.BooleanField(default=True, help_text='Receive email when appointment is approved')),
                ('email_appointment_reminder', models.BooleanField(default=True, help_text='Receive appointment reminder emails')),
                ('email_request_status', models.BooleanField(default=True, help_text='Receive email when update request status changes')),
                ('email_certificate_issued', models.BooleanField(default=True, help_text='Receive email when certificate is issued')),
                ('email_system_notifications', models.BooleanField(default=True, help_text='Receive system notification emails')),
                ('inapp_appointment_updates', models.BooleanField(default=True, help_text='Show in-app notifications for appointments')),
                ('inapp_request_updates', models.BooleanField(default=True, help_text='Show in-app notifications for requests')),
                ('inapp_system_notifications', models.BooleanField(default=True, help_text='Show system notifications in-app')),
                ('appointment_reminder_hours', models.PositiveIntegerField(default=24, help_text='Hours before appointment to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('appointment_approved', 'Appointment Approved'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('request_approved', 'Update Request Approved'), ('request_declined', 'Update Request Declined'), ('request_expiring', 'Request Expiring Soon'), ('certificate_issued', 'Certificate Issued'), ('prescription_issued', 'Prescription Issued'), ('system', 'System Notification'), ('other', 'Other')], default='system', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('action_url', models.CharField(blank=True, help_text='URL for action button', max_length=500, null=True)),
                ('action_label', models.CharField(blank=True, help_text='Label for action button', max_length=100, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., Appointment, Certificate)', max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of related object', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('send_email', models.BooleanField(default=False, help_text='Whether to send email notification')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires and can be auto-deleted', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(help_text='Email recipient address', max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('body', models.TextField(help_text='Email body content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of send attempts')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email'], name='notificatio_recipie_25af1a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_6192b4_idx'),
        ),
    ]
